repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.4'
    hooks:
    -   id: autopep8
        args: ["-i", "-j 4"]
-   repo: local
    hooks:
        - id: autoflake
          name: autoflake
          entry: autoflake
          language: python
          types: [ python ]
          args: [
              "--in-place",
              "-r",
              ".",
          ]
        - id: black
          name: black
          entry: black .
          language: python
          types: [python]

        - id: isort
          name: isort
          entry: isort .
          language: python
          types: [python]

        - id: ruff
          name: ruff
          entry: ruff check --force-exclude .
          args: [--fix]
          language: python
          types: [python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        additional_dependencies: [
            'django-stubs',
            'types-python-dateutil',
            'types-requests',
            'celery',
            'sentry-sdk',
            'environs',
            'django-cors-headers',
            'djangorestframework',
            'djangorestframework-simplejwt',
            'drf-spectacular',
            'dj-rest-auth',
            'django-filter',
            'django-mail-admin',
            'django-celery-beat',
            'django-minio-backend',
            'psycopg2-binary',
            'django-oauth-toolkit',
            'social-auth-app-django',
            'drf_social_oauth2',
            'django_admin_inline_paginator',
        ]
